export const NEXT_QUESTION = 'NEXT_QUESTION';
export const ANSWER_SUBMITTED = 'ANSWER_SUBMITTED';
export const ANSWER_KEY = 'ANSWER_KEY';
export const QUIZ_RESULTS = 'QUIZ_RESULTS';
export const START_NEW_QUIZ = 'START_NEW_QUIZ';
export const CORRECT_ANSWER = 'CORRECT_ANSWER';
export const INCORRECT_ANSWER = 'INCORRECT_ANSWER';
export const START_DATA = 'START_DATA'; // begin api data retrieval -> activity indicator
export const DATA_AVAILABLE = 'DATA_AVAILABLE'; // data retrieved
// export const FADE_IN_QUIZ = 'FADE_IN_QUIZ'; // @todo not being used?
// export const FADE_OUT_QUIZ = 'FADE_OUT_QUIZ'; // @todo not being used?
